# image: node:18

# pipelines:
#   branches:
#     master:
#       - step:
#           name: Install, Build, Push to Dist
#           caches:
#             - node
#           script:
#             - npm ci
#             - npm run build:ssr
#             - git config --global user.email "manukyanharut1994@gmail.com"
#             - git config --global user.name "HaRuT-1994"

#             - git checkout --orphan dist
#             - git rm -rf .
#             - cp -r dist/* .
#             - rm -rf dist
#             - rm -rf node_modules
#             - git add .
#             - git commit -m "release"
#             - git push origin dist --force
#             - VERSION=$(node -p "require('./package.json').version")
#             - git tag "v$VERSION"
#             - git push origin "v$VERSION"
